swipe:
  3:
    left:
      command: exec i3 focus left
    right:
      command: exec i3 focus right
    up:
      command: exec i3 focus up
    down:
      command: exec i3 focus down
  4:
    left:
     command: exec i3 workspace prev
    right:
      command: exec i3 workspace next
    up:
      command: exec i3 fullscreen toggle
    down:
      command: exec i3 floating toggle
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
     command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.6
