#!/bin/bash
# changeVolume

# Arbitrary but unique message id
msgId="991049"

# Change the volume using alsa(might differ if you use pulseaudio)
#amixer -c 0 set Master "$@" > /dev/null

# Query amixer for the current volume and whether or not the speaker is muted
volume="$(pamixer --get-volume)"
mute="$(pamixer --get-mute)"
bar="$(seq -s '' $(($volume / 3)) | sed 's/[0-9]//g')"
if [[ $volume == 0 || $mute == true ]]; then
    # Show the sound muted notification
    dunstify -u low --icon=/usr/share/icons/la-capitaine-icon-theme/actions/22x22-dark/player-volume-muted.svg -r "$msgId" "Звук выключен" 
elif [[ $volume -ge 105 ]]; then
    # Show the sound max notification
    pactl set-sink-volume @DEFAULT_SINK@ 100%
else
    # Show the volume notification
    dunstify -u low --icon=/usr/share/icons/la-capitaine-icon-theme/actions/22x22-dark/player-volume.svg -r "$msgId" " ${bar}"
fi

# Play the volume changed sound
#canberra-gtk-play -i audio-volume-change -d "changeVolume"
